# Simple compose file for local image testing
version: "3"

services:
  flask-app:
    build:
      context: ./flask_app
    environment:
      POSTGRES_CONNECTION_STRING: postgres://foo:1234
      REDIS_HOST: moo
      REDIS_PORT: 1234
    ports:
      - 9000:8000

  react-frontend:
    build:
      context: ./react_frontend
    environment:
      API_URL: http://localhost:9000
    ports:
      - 8080:1234