#
# CircleCI configuration file
#
version: 2.1

#
# Common vars
#
var_docker_default: &default_docker
    docker:
        - image: circleci/python:3.8-buster

#
# Job definitions
#
jobs:
    build-flask-app:
        <<: *default_docker
        working_directory: ~/repo
        steps:
            - checkout:
                path: ~/repo
            - setup_remote_docker
            - run:
                name: Build docker image
                command: |
                    cd ~/repo/.scripts
                    ./build_docker_image.sh

#
# Workflows
#
workflows:
    version: 2
    build-test-deploy-flask-app:
        jobs:
            - build-flask-app