#! /bin/bash

set -e

cd ../

# Clean up
docker-compose -f ./docker-compose.e2e.yml down

# Run e2e with compose
echo "Running e2e tests"
docker-compose -f ./docker-compose.e2e.yml up -d --build
sleep 2
docker logs hanzo-cypress-tests --follow &
run_result=$(docker wait hanzo-cypress-tests)
docker-compose -f ./docker-compose.e2e.yml stop

rm -rf e2e-results
rm -rf e2e-logs
mkdir -p ./e2e-results
mkdir -p ./e2e-logs

# Copy run results
docker cp hanzo-cypress-tests:/cypress_tests/cypress/videos ./e2e-results/videos || true
docker cp hanzo-cypress-tests:/cypress_tests/cypress/screenshots ./e2e-results/screenshots || true
docker cp hanzo-cypress-tests:/cypress_tests/cypress/junit ./e2e-results/junit || true

if [ ! -f ./e2e-results/junit/test-results.xml ]; then
  echo "No test results generated by test run, aborting"
  exit 1;
fi

if [ "$run_result" = "1" ]; then
  echo "e2e test run failed ¯\_(ツ)_/¯"
  echo "Dumping logs"
  docker-compose -f ./docker-compose.e2e.yml logs --no-color > ./e2e-logs/compose.log
  exit 1;
fi

echo "e2e test run passed, yey ヽ(´▽\`)/"
echo "Dumping logs"
docker-compose -f ./docker-compose.e2e.yml logs --no-color > ./e2e-logs/compose.log